// Run once after migrations: npx tsx prisma/import.ts
import { PrismaPg } from '@prisma/adapter-pg'
import { PrismaClient } from '@prisma/client'

if (!process.env.DATABASE_URL) throw new Error('DATABASE_URL is not set')
const adapter = new PrismaPg(process.env.DATABASE_URL)
const prisma = new PrismaClient({ adapter })

const songs = [
  // IN_PROGRESS
  { title: 'Sugar Magnolia', artist: 'Grateful Dead', status: 'IN_PROGRESS', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Birthday', artist: 'Beatles', status: 'IN_PROGRESS', singer: null, key: 'A', keyboardRequired: false, durationSeconds: null },
  { title: 'Do You Feel', artist: 'Peter Frampton', status: 'IN_PROGRESS', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Drowned', artist: 'The Who', status: 'IN_PROGRESS', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Eminence Front', artist: 'The Who', status: 'IN_PROGRESS', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Faeiries Wear Boots', artist: 'Black Sabbath', status: 'IN_PROGRESS', singer: 'Andrew', key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Fly like an Eagle', artist: 'Steve Miller', status: 'IN_PROGRESS', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Frankenstein', artist: 'Edgar Winter', status: 'IN_PROGRESS', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Lawyers Guns & Money', artist: 'Warren Zevon', status: 'IN_PROGRESS', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Ramble On', artist: 'Led Zeppelin', status: 'IN_PROGRESS', singer: 'Jeff', key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Soul Kitchen', artist: 'The Doors', status: 'IN_PROGRESS', singer: 'Jeff', key: null, keyboardRequired: true, durationSeconds: null },
  { title: 'Tell the Truth', artist: 'Derek & The Dominoes', status: 'IN_PROGRESS', singer: 'Jeff', key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'The Weight', artist: 'The Band', status: 'IN_PROGRESS', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Tumblin Dice', artist: 'Rolling Stones', status: 'IN_PROGRESS', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Viola Lee Blues', artist: 'Grateful Dead', status: 'IN_PROGRESS', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Nights in White Satin', artist: 'Moody Blues', status: 'IN_PROGRESS', singer: null, key: null, keyboardRequired: false, durationSeconds: 300 },
  { title: 'Brick > Shakedown', artist: 'Pink Floyd / Grateful Dead', status: 'IN_PROGRESS', singer: 'Jeff', key: 'Dm', keyboardRequired: false, durationSeconds: null },
  { title: 'China > Pocky > Rider', artist: 'Grateful Dead', status: 'IN_PROGRESS', singer: 'J/S/J', key: 'G/D/D', keyboardRequired: false, durationSeconds: null },
  { title: "Don't Let Me Down > Eyes of the World", artist: 'Beatles / Grateful Dead', status: 'IN_PROGRESS', singer: 'Jeff', key: 'E/F#m', keyboardRequired: false, durationSeconds: null },
  // READY
  { title: 'Cayman Review', artist: 'Trey Anastasio', status: 'READY', singer: 'Jeff', key: 'E', keyboardRequired: false, durationSeconds: null },
  { title: 'Cheap Sunglasses', artist: 'ZZ Top', status: 'READY', singer: 'Andrew', key: 'Gm', keyboardRequired: false, durationSeconds: 325 },
  { title: 'Crossroads', artist: 'Cream', status: 'READY', singer: 'Jeff', key: 'A', keyboardRequired: false, durationSeconds: null },
  { title: '25 or 6 to 4', artist: 'Chicago', status: 'READY', singer: null, key: 'C', keyboardRequired: false, durationSeconds: null },
  { title: 'Almost Cut My Hair', artist: 'CSNY', status: 'READY', singer: null, key: 'Am', keyboardRequired: false, durationSeconds: null },
  { title: 'Althea', artist: 'Grateful Dead', status: 'READY', singer: 'Rich', key: 'Bm', keyboardRequired: false, durationSeconds: null },
  { title: 'Another Brick in the Wall', artist: 'Pink Floyd', status: 'READY', singer: 'Jeff', key: 'Dm', keyboardRequired: false, durationSeconds: 240 },
  { title: 'Arcadia', artist: 'Goose', status: 'READY', singer: 'Jeff', key: 'C#', keyboardRequired: false, durationSeconds: null },
  { title: 'Bertha', artist: 'Grateful Dead', status: 'READY', singer: 'Rich', key: 'G', keyboardRequired: false, durationSeconds: 425 },
  { title: 'Blue Sky', artist: 'Allman Brothers', status: 'READY', singer: 'Jeff', key: 'E', keyboardRequired: false, durationSeconds: 362 },
  { title: 'Born on the Bayou', artist: 'CCR', status: 'READY', singer: 'Jeff', key: null, keyboardRequired: false, durationSeconds: 300 },
  { title: 'Breathe', artist: 'Pink Floyd', status: 'READY', singer: 'Jeff', key: 'Em', keyboardRequired: false, durationSeconds: 240 },
  { title: 'Brown Eyed Women', artist: 'Grateful Dead', status: 'READY', singer: null, key: 'E/C#m', keyboardRequired: false, durationSeconds: 420 },
  { title: 'Burning Down the House', artist: 'Talking Heads', status: 'READY', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Call Me The Breeze', artist: 'Lynyrd Skynyrd', status: 'READY', singer: 'Jeff', key: 'A', keyboardRequired: false, durationSeconds: 314 },
  { title: 'China Cat', artist: 'Grateful Dead', status: 'READY', singer: 'J/S/J', key: 'G', keyboardRequired: false, durationSeconds: 300 },
  { title: 'Cinnamon Girl', artist: 'Neil Young', status: 'READY', singer: null, key: 'Am/D', keyboardRequired: false, durationSeconds: 254 },
  { title: 'Come and Go Blues', artist: 'Allman Brothers', status: 'READY', singer: 'Jeff', key: 'G', keyboardRequired: true, durationSeconds: null },
  { title: 'Come Together', artist: 'Beatles', status: 'READY', singer: 'Jeff', key: 'Dm', keyboardRequired: false, durationSeconds: 300 },
  { title: 'Deal', artist: 'Grateful Dead', status: 'READY', singer: 'Rich', key: 'A', keyboardRequired: false, durationSeconds: null },
  { title: 'Deep Elem Blues', artist: 'Grateful Dead', status: 'READY', singer: 'Jeff', key: 'E', keyboardRequired: false, durationSeconds: 240 },
  { title: "Don't Let Me Down", artist: 'Beatles / Grateful Dead', status: 'READY', singer: 'Jeff', key: 'E/F#m', keyboardRequired: false, durationSeconds: 300 },
  { title: 'Down By The River', artist: 'Neil Young', status: 'READY', singer: 'Scott', key: 'Em', keyboardRequired: false, durationSeconds: 480 },
  { title: 'Eyes of the World', artist: 'Grateful Dead', status: 'READY', singer: 'Jeff', key: 'E', keyboardRequired: false, durationSeconds: 450 },
  { title: "Feelin' Alright", artist: 'Joe Cocker', status: 'READY', singer: 'Guller', key: 'C', keyboardRequired: true, durationSeconds: null },
  { title: 'Fire On the Mountain', artist: 'Grateful Dead', status: 'READY', singer: 'Jeff', key: 'B mix', keyboardRequired: false, durationSeconds: 420 },
  { title: "Franklin's Tower", artist: 'Grateful Dead', status: 'READY', singer: 'Jeff', key: 'A', keyboardRequired: false, durationSeconds: 390 },
  { title: 'Free', artist: 'Phish', status: 'READY', singer: 'Jeff', key: 'D', keyboardRequired: false, durationSeconds: null },
  { title: 'Friend of the Devil', artist: 'Grateful Dead', status: 'READY', singer: 'Rich', key: 'G', keyboardRequired: false, durationSeconds: 270 },
  { title: 'Gimme Shelter', artist: 'Rolling Stones', status: 'READY', singer: 'Jeff', key: 'C#', keyboardRequired: false, durationSeconds: 300 },
  { title: 'Going Down The Road', artist: 'Grateful Dead', status: 'READY', singer: null, key: 'E', keyboardRequired: false, durationSeconds: 360 },
  { title: 'Golden Years', artist: 'David Bowie', status: 'READY', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Hard To Handle', artist: 'Black Crowes', status: 'READY', singer: 'Jeff', key: 'B', keyboardRequired: false, durationSeconds: 330 },
  { title: 'Heard it Thru the Grapevine', artist: 'Marvin Gaye', status: 'READY', singer: 'Jeff', key: 'Am', keyboardRequired: false, durationSeconds: 720 },
  { title: 'Hello LA, Bye-bye Birminham', artist: 'Chris Robinson', status: 'READY', singer: 'Jeff', key: 'E', keyboardRequired: false, durationSeconds: 300 },
  { title: 'Hey Pocky Way', artist: 'The Meters', status: 'READY', singer: 'J/S/J', key: 'Dm', keyboardRequired: false, durationSeconds: 240 },
  { title: 'I Know You Rider', artist: 'Grateful Dead', status: 'READY', singer: 'J/S/J', key: 'Dm', keyboardRequired: false, durationSeconds: 390 },
  { title: "I'm a Hog for You Baby", artist: 'Grateful Dead', status: 'READY', singer: 'Jeff', key: 'G', keyboardRequired: false, durationSeconds: null },
  { title: "I've Got a Feeling", artist: 'The Beatles', status: 'READY', singer: 'Jeff', key: 'G', keyboardRequired: false, durationSeconds: 270 },
  { title: 'In Memory of Elizabeth Reed', artist: 'Allman Brothers', status: 'READY', singer: null, key: 'Am', keyboardRequired: false, durationSeconds: null },
  { title: 'Into the Mystic', artist: 'Van Morrison', status: 'READY', singer: 'Jeff', key: null, keyboardRequired: false, durationSeconds: null },
  { title: "It's All Over Now, Baby Blue", artist: 'Bob Dylan', status: 'READY', singer: 'Jeff', key: 'Dm', keyboardRequired: false, durationSeconds: null },
  { title: 'Jack Straw', artist: 'Grateful Dead', status: 'READY', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Jet Airliner', artist: 'Steve Miller', status: 'READY', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Keep On Growing', artist: 'Derek and the Dominos', status: 'READY', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Lay Down Sally', artist: 'Eric Clapton', status: 'READY', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Leave Your Hat On', artist: 'Joe Cocker', status: 'READY', singer: 'Jeff', key: null, keyboardRequired: false, durationSeconds: null },
  { title: "Let's Dance", artist: 'David Bowie', status: 'READY', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Let it Rain', artist: 'Eric Clapton', status: 'READY', singer: 'Jeff', key: 'A', keyboardRequired: false, durationSeconds: 330 },
  { title: 'Listen To the Music', artist: 'Doobie Brothers', status: 'READY', singer: null, key: null, keyboardRequired: false, durationSeconds: 279 },
  { title: 'Liza Jane', artist: 'Vince Gill', status: 'READY', singer: 'Jeff', key: null, keyboardRequired: false, durationSeconds: null },
  { title: "Long Train Runnin'", artist: 'Doobie Brothers', status: 'READY', singer: 'Jeff', key: null, keyboardRequired: false, durationSeconds: 290 },
  { title: "Mary Jane's Last Dance", artist: 'Tom Petty', status: 'READY', singer: 'Jeff', key: null, keyboardRequired: false, durationSeconds: 266 },
  { title: 'Me and My Uncle', artist: 'Grateful Dead', status: 'READY', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Mr. Charlie', artist: 'Grateful Dead', status: 'READY', singer: 'Jeff', key: null, keyboardRequired: false, durationSeconds: 270 },
  { title: 'New Minglewood Blues', artist: 'Grateful Dead', status: 'READY', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Not Fade Away', artist: 'Buddy Holly', status: 'READY', singer: 'Jeff', key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Ohio (with Find the Cost of Freedom)', artist: 'CSNY', status: 'READY', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'One Way Out', artist: 'Allman Brothers', status: 'READY', singer: 'Jeff', key: 'A', keyboardRequired: false, durationSeconds: 317 },
  { title: 'Ophelia', artist: 'The Band', status: 'READY', singer: 'Jeff', key: 'C', keyboardRequired: false, durationSeconds: 240 },
  { title: 'Play That Funky Music', artist: 'Wild Cherry', status: 'READY', singer: 'Jeff', key: 'E', keyboardRequired: false, durationSeconds: null },
  { title: 'Rain', artist: 'The Beatles', status: 'READY', singer: 'Jeff', key: 'G', keyboardRequired: false, durationSeconds: 240 },
  { title: 'Rebel, Rebel', artist: 'David Bowie', status: 'READY', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Remedy', artist: 'Black Crowes', status: 'READY', singer: 'Jeff', key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Roses are Free', artist: 'Ween', status: 'READY', singer: 'Jeff', key: null, keyboardRequired: false, durationSeconds: 240 },
  { title: 'Scarlet Begonias', artist: 'Grateful Dead', status: 'READY', singer: 'Jeff', key: null, keyboardRequired: false, durationSeconds: 360 },
  { title: 'Scarlet > Fire', artist: 'Grateful Dead', status: 'READY', singer: 'Jeff', key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Shakedown Street', artist: 'Grateful Dead', status: 'READY', singer: 'Jeff', key: null, keyboardRequired: false, durationSeconds: 660 },
  { title: "Shape I'm In", artist: 'The Band', status: 'READY', singer: 'Jeff', key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Soulshine', artist: 'Allman Brothers', status: 'READY', singer: 'Jeff', key: 'Bb', keyboardRequired: false, durationSeconds: 360 },
  { title: 'Space Cowboy', artist: 'Steve Miller', status: 'READY', singer: 'Jeff', key: null, keyboardRequired: false, durationSeconds: 330 },
  { title: 'Sugaree', artist: 'Grateful Dead', status: 'READY', singer: 'Jeff', key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Sultans of Swing', artist: 'Dire Straits', status: 'READY', singer: 'Andrew', key: null, keyboardRequired: false, durationSeconds: 381 },
  { title: 'Superstition', artist: 'Stevie Wonder', status: 'READY', singer: 'Jeff', key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Sympathy for the Devil', artist: 'Rolling Stones', status: 'READY', singer: 'Jeff', key: null, keyboardRequired: false, durationSeconds: 441 },
  { title: 'Take it Easy', artist: 'Eagles', status: 'READY', singer: 'Jeff', key: 'G', keyboardRequired: false, durationSeconds: null },
  { title: 'Take Me to the River', artist: 'Talking Heads', status: 'READY', singer: 'Jeff', key: null, keyboardRequired: false, durationSeconds: 375 },
  { title: "That's What Love Will Make You Do", artist: 'Jerry Garcia Band', status: 'READY', singer: 'Guller', key: 'C', keyboardRequired: false, durationSeconds: null },
  { title: 'The Letter', artist: 'Joe Cocker', status: 'READY', singer: null, key: null, keyboardRequired: false, durationSeconds: 240 },
  { title: 'Throwing Stones', artist: 'Grateful Dead', status: 'READY', singer: 'Jeff', key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Trouble No More', artist: 'Allman Brothers', status: 'READY', singer: 'Jeff', key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Truckin', artist: 'Grateful Dead', status: 'READY', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Two Tickets To Paradise', artist: 'Eddie Money', status: 'READY', singer: null, key: null, keyboardRequired: false, durationSeconds: 290 },
  { title: 'U.S. Blues', artist: 'Grateful Dead', status: 'READY', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Werewolves of London', artist: 'Warren Zevon', status: 'READY', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Whipping Post', artist: 'Allman Brothers', status: 'READY', singer: null, key: null, keyboardRequired: false, durationSeconds: 450 },
  { title: 'White Room', artist: 'Cream', status: 'READY', singer: 'Jeff', key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Wild Night', artist: 'Van Morrison', status: 'READY', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: "You Can't Always Get What you Want", artist: 'Rolling Stones', status: 'READY', singer: 'Jeff', key: null, keyboardRequired: false, durationSeconds: null },
  // WISH
  { title: 'After Midnight', artist: 'Eric Clapton', status: 'WISH', singer: null, key: 'C', keyboardRequired: false, durationSeconds: null },
  { title: "Ain't Wastin Time No More", artist: 'Allman Brothers', status: 'WISH', singer: null, key: 'Bb', keyboardRequired: true, durationSeconds: null },
  { title: 'Almost Cut My Hair > 25 or 6 to 4', artist: 'CSNY / Chicago', status: 'WISH', singer: 'Jeff', key: 'Am/C', keyboardRequired: false, durationSeconds: null },
  { title: 'Bad', artist: 'U2', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Big River', artist: 'Johnny Cash', status: 'WISH', singer: null, key: 'G', keyboardRequired: false, durationSeconds: null },
  { title: 'Bird Song', artist: 'Grateful Dead', status: 'WISH', singer: null, key: 'E', keyboardRequired: false, durationSeconds: null },
  { title: 'Boogie on Reggae Woman', artist: 'Stevie Wonder', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Born Under a Bad Sign', artist: 'Cream', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'China Girl', artist: 'David Bowie', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Cortez the Killer', artist: 'Neil Young', status: 'WISH', singer: null, key: 'Am', keyboardRequired: false, durationSeconds: null },
  { title: 'Cripple Creek', artist: 'The Band', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Dancing in the Moonlight', artist: 'King Harvest', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Dancing in the Streets', artist: 'Martha and the Vandellas', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Dear Prudence', artist: 'The Beatles', status: 'WISH', singer: null, key: 'D', keyboardRequired: false, durationSeconds: null },
  { title: 'Dire Wolf', artist: 'Grateful Dead', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Dixie Chicken', artist: 'Little Feat', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Doctor my Eyes', artist: 'Jackson Browne', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: "Don't Do It", artist: 'The Band', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: "Don't let Me Be Misunderstood", artist: 'The Animals', status: 'WISH', singer: null, key: 'Am', keyboardRequired: false, durationSeconds: null },
  { title: 'Down by the River > Breathe', artist: 'Neil Young / Pink Floyd', status: 'WISH', singer: 'S/J', key: 'Em', keyboardRequired: false, durationSeconds: null },
  { title: 'Dreams', artist: 'Allman Brothers', status: 'WISH', singer: 'Jeff', key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Eleanor Rigby', artist: 'The Beatles', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: "Feelin Alright / Can't Always Get What You Want", artist: 'Joe Cocker / Rolling Stones', status: 'WISH', singer: null, key: 'C', keyboardRequired: true, durationSeconds: null },
  { title: 'Flowers', artist: 'Miley Cyrus', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: "For What It's Worth", artist: 'Buffalo Springfield', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Gimme 3 Steps', artist: 'Lynyrd Skynyrd', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: "Good Lovin'", artist: 'Rascals / Grateful Dead', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Green River', artist: 'CCR', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Heaven', artist: 'Los Lonely Boys', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Heroes', artist: 'David Bowie', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'How Sweet it Is', artist: 'James Taylor', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'I Put a Spell on You', artist: 'CCR', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'I Second that Emotion', artist: 'Smokey Robinson', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Jealous Again', artist: 'Black Crowes', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Josie', artist: 'Steely Dan', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: "Keep On Growin' > Franklin's > Blue Sky", artist: 'Derek > Grateful Dead > Allman Brothers', status: 'WISH', singer: 'Jeff', key: null, keyboardRequired: false, durationSeconds: null },
  { title: "Knockin on Heaven's Door", artist: 'Bob Dylan', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Learning to Fly', artist: 'Pink Floyd', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Like a Hurricane', artist: 'Neil Young', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Loser', artist: 'Grateful Dead', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Low Spark of High Heeled Boys', artist: 'Traffic', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Magic Carpet Ride', artist: 'Steppenwolf', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Melissa', artist: 'Allman Brothers', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Midnight Moonlight', artist: 'Jerry Garcia', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Midnight Rider', artist: 'Allman Brothers', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Midnight Special', artist: 'CCR', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Mississippi Half Step', artist: 'Grateful Dead', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Morning Dew', artist: 'Grateful Dead', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Mountain Jam', artist: 'Allman Brothers', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'My Old School', artist: 'Steely Dan', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Norwegian Wood', artist: 'The Beatles', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Roadhouse Blues', artist: 'The Doors', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Rock & Roll', artist: 'Velvet Underground', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Seeker', artist: 'The Who', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'She Said, She Said', artist: 'The Beatles', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: "She's So Heavy", artist: 'The Beatles', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Simple Man', artist: 'Lynyrd Skynyrd', status: 'WISH', singer: 'Jeff', key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Sir Duke', artist: 'Stevie Wonder', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Sneaking Sally Thru the Alley', artist: 'Robert Palmer', status: 'WISH', singer: 'Jeff', key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'South City Midnight Lady', artist: 'Doobie Brothers', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Sweet Jane', artist: 'Lou Reed', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Take Me to the River > Bayou', artist: 'Talking Heads / CCR', status: 'WISH', singer: 'Jeff', key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'They Love Each Other', artist: 'Grateful Dead', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Too Sweet', artist: 'Hozier', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Turn to Stone', artist: 'Joe Walsh', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Victim of Love', artist: 'The Eagles', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Wah Wah', artist: 'George Harrison', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: "What's Goin' On", artist: 'Marvin Gaye', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
  { title: 'Wiser Time', artist: 'Black Crowes', status: 'WISH', singer: null, key: null, keyboardRequired: false, durationSeconds: null },
]

const venues = [
  { name: "Luv'n Oven" },
  { name: "Galuppi's" },
  { name: "Sharkey's" },
  { name: 'Boca Tiki Bar' },
  { name: 'Ellis' },
  { name: 'Christa' },
  { name: 'LauderAle' },
  { name: 'Coconut Creek' },
  { name: "Lefty's" },
  { name: 'The Walk' },
  { name: 'The Bungalow' },
  { name: "Robin's Ranch" },
  { name: 'Pomp Brew' },
  { name: 'Marina 84' },
  { name: 'MGV' },
  { name: 'Pomp Beach Starlight' },
  { name: 'Century Village' },
  { name: 'Margaritaville' },
  { name: 'Gigi' },
  { name: 'PBB' },
]

async function main() {
  const existingSongs = await (prisma as any).song.count()
  if (existingSongs > 0) {
    console.log(`Database already has ${existingSongs} songs — skipping song import.`)
    console.log('To re-import, clear the songs table first.')
  } else {
    console.log(`Importing ${songs.length} songs…`)
    const result = await (prisma as any).song.createMany({ data: songs })
    console.log(`  Created ${result.count} songs.`)
  }

  const existingVenues = await (prisma as any).venue.count()
  if (existingVenues > 0) {
    console.log(`Database already has ${existingVenues} venues — skipping venue import.`)
  } else {
    console.log(`Importing ${venues.length} venues…`)
    const result = await (prisma as any).venue.createMany({ data: venues })
    console.log(`  Created ${result.count} venues.`)
  }

  console.log('Done!')
}

main()
  .catch((e) => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())
